name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mtinti
        password: ${{ secrets.DOCKER_PAT }}
    
    - name: Build and push the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: mtinti/rna_seq:latest